#!/bin/bash -e

babel=$RACKT_PATH/node_modules/.bin/babel
webpack=$RACKT_PATH/node_modules/.bin/webpack

# Clean old build
rm -rf build/

# Generate bundle for NPM
$webpack --devtool source-map --config ./webpack.build.js --output-path ./build --output-filename index.js

# Copy package
cp README.md build/
node -p 'p=require("./package");p.scripts=p.devDependencies=undefined;p.main="./index.js";JSON.stringify(p,null,2)' > build/package.json
