#!/bin/bash

server=$RACKT_PATH/node_modules/.bin/webpack-dev-server

# get available PORT
PORT=`$RACKT_PATH/tasks/getAvailablePort`

$server --inline --config ./webpack.config.js --host 0.0.0.0 --port $PORT --content-base examples/ "$@"
